name: 'Setup ROS2 environment'
description: 'Install ROS 2 from source on the host machine'
author: 'ROS Tooling Working Group'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'dist/index.js'
